// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/yogihardi/goa-vendor/design
// --out=$(GOPATH)/src/github.com/yogihardi/goa-vendor
// --version=v1.1.0-dirty
//
// API "cellar": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// BottleHref returns the resource href.
func BottleHref(bottleID interface{}) string {
	parambottleID := strings.TrimLeftFunc(fmt.Sprintf("%v", bottleID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/bottles/%v", parambottleID)
}
