// Code generated by goagen v1.1.0, command line:
// $ goagen
// --design=github.com/yogihardi/goa-vendor/design
// --out=$(GOPATH)/src/github.com/yogihardi/goa-vendor
// --version=v1.1.0-dirty
//
// API "cellar": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
